### PR TITLE
Refactor replacement

### PR DESCRIPTION
**Pull request by zcabjro**
Functionally the same, just with some bits of the extension extracted into separate modules.

Also added some simple tests for the text replace logic 🎉

### CODE REVIEW

**Comment by zcabjro** [comment]
Related to #1

**Comment by sandcastle** [comment]
@zcabjro thanks for the PR 👍

**Comment by sandcastle** [comment]
@zcabjro this has now been published to vscode marketplace 🚀

**Comment by zcabjro** [comment]
Awesome! Thanks for the helpful extension.

**Pull request merged**
